import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const TELEGRAM_BOT_TOKEN = Deno.env.get('TELEGRAM_BOT_TOKEN');
    const TELEGRAM_CHAT_ID = Deno.env.get('TELEGRAM_CHAT_ID');
    const SUPABASE_URL = Deno.env.get('SUPABASE_URL');
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!TELEGRAM_BOT_TOKEN || !TELEGRAM_CHAT_ID) {
      console.error('Missing Telegram credentials');
      throw new Error('Missing Telegram credentials');
    }

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      console.error('Missing Supabase credentials');
      throw new Error('Missing Supabase credentials');
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Get today's date range (start and end of day in UTC)
    const today = new Date();
    const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 0, 0, 0, 0);
    const endOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate(), 23, 59, 59, 999);

    console.log(`Fetching completed payments from ${startOfDay.toISOString()} to ${endOfDay.toISOString()}`);

    // Fetch all completed payments for today
    const { data: payments, error: paymentsError } = await supabase
      .from('mpesa_payments')
      .select('amount, transaction_code, customer_name, phone_number, created_at')
      .eq('payment_status', 'COMPLETED')
      .gte('created_at', startOfDay.toISOString())
      .lte('created_at', endOfDay.toISOString())
      .order('created_at', { ascending: false });

    if (paymentsError) {
      console.error('Error fetching payments:', paymentsError);
      throw paymentsError;
    }

    console.log(`Found ${payments?.length || 0} completed payments for today`);

    // Calculate total
    const totalAmount = (payments || []).reduce((sum, payment) => sum + (payment.amount || 0), 0);
    const transactionCount = payments?.length || 0;

    // Format the message
    const dateStr = today.toLocaleDateString('en-KE', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });

    let message = `📊 *DAILY TRANSACTION SUMMARY*\n`;
    message += `📅 ${dateStr}\n\n`;
    message += `━━━━━━━━━━━━━━━━━━━━━━\n`;
    message += `💰 *Total Completed: KES ${totalAmount.toLocaleString()}*\n`;
    message += `📝 *Transactions: ${transactionCount}*\n`;
    message += `━━━━━━━━━━━━━━━━━━━━━━\n\n`;

    if (transactionCount > 0) {
      message += `📋 *Transaction Details:*\n\n`;
      
      (payments || []).forEach((payment, index) => {
        const time = new Date(payment.created_at).toLocaleTimeString('en-KE', { 
          hour: '2-digit', 
          minute: '2-digit' 
        });
        message += `${index + 1}. ${payment.customer_name || 'N/A'}\n`;
        message += `   📱 ${payment.phone_number || 'N/A'}\n`;
        message += `   💵 KES ${(payment.amount || 0).toLocaleString()}\n`;
        message += `   🧾 ${payment.transaction_code || 'N/A'}\n`;
        message += `   🕐 ${time}\n\n`;
      });
    } else {
      message += `ℹ️ No completed transactions for today.\n`;
    }

    message += `\n_Generated by Ziada Loans System_`;

    // Send to Telegram
    const telegramUrl = `https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`;
    
    const telegramResponse = await fetch(telegramUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        chat_id: TELEGRAM_CHAT_ID,
        text: message,
        parse_mode: 'Markdown',
      }),
    });

    const telegramResult = await telegramResponse.json();

    if (!telegramResponse.ok) {
      console.error('Telegram API error:', telegramResult);
      throw new Error(`Telegram API error: ${JSON.stringify(telegramResult)}`);
    }

    console.log('Telegram message sent successfully:', telegramResult);

    return new Response(
      JSON.stringify({ 
        success: true, 
        totalAmount, 
        transactionCount,
        message: 'Daily summary sent to Telegram'
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200 
      }
    );

  } catch (error) {
    console.error('Error in telegram-daily-summary:', error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
