// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xxfybuqajtejzthyszam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZnlidXFhanRlanp0aHlzemFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTk3MDIsImV4cCI6MjA2OTg3NTcwMn0.aoIuzjssllzRnlDQRHTc3hfT8IF3y3XW7qkYHHt8p_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
